-- 1. SECUENCIA PARA GENERAR LOS ID DE LOS PRODUCTOS.
CREATE SEQUENCE SEQ_PRODUCTOS
START WITH 20
INCREMENT BY 1;

-- 2. VISTA (View): UNE PRODUCTOS CON CATEGORIAS PARA MOSTRAR EL NOMBRE DE LA CATEGORIA.
CREATE OR REPLACE VIEW V_DETALLE_PRODUCTOS AS
SELECT 
    p.ID_PRODUCTO,
    p.NOMBRE AS NOMBRE_PRODUCTO,
    p.PRECIO,
    p.STOCK,
    c.NOMBRE AS CATEGORIA,
    p.ESTADO,
    p.FECHA_REGISTRO
FROM PRODUCTOS_TIENDA p
JOIN CATEGORIAS c ON p.ID_CATEGORIA = c.ID_CATEGORIA
ORDER BY p.ID_PRODUCTO ASC;

-- PROCEDIMIENTO PARA INSERTAR PRODUCTO
CREATE OR REPLACE PROCEDURE SP_INSERTAR_PRODUCTO (
    p_nombre IN VARCHAR2,
    p_precio IN NUMBER,
    p_stock IN NUMBER,
    p_id_categoria IN NUMBER,
    p_estado IN VARCHAR2
) AS
BEGIN
    INSERT INTO PRODUCTOS_TIENDA (ID_PRODUCTO, NOMBRE, PRECIO, STOCK, ID_CATEGORIA, ESTADO, FECHA_REGISTRO)
    VALUES (SEQ_PRODUCTOS.NEXTVAL, p_nombre, p_precio, p_stock, p_id_categoria, p_estado, SYSDATE);
    COMMIT;
END;
/

-- PROCEDIMIENTO PARA ACTUALIZAR PRODUCTO
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_PRODUCTO (
    p_id IN NUMBER,
    p_nombre IN VARCHAR2,
    p_precio IN NUMBER,
    p_stock IN NUMBER,
    p_estado IN VARCHAR2
) AS
BEGIN
    UPDATE PRODUCTOS_TIENDA
    SET NOMBRE = p_nombre,
        PRECIO = p_precio,
        STOCK = p_stock,
        ESTADO = p_estado
    WHERE ID_PRODUCTO = p_id;
    COMMIT;
END;
/

-- PROCEDIMIENTO PARA ELIMINAR PRODUCTO.
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_PRODUCTO (
    p_id IN NUMBER
) AS
BEGIN
    DELETE FROM PRODUCTOS_TIENDA WHERE ID_PRODUCTO = p_id;
    COMMIT;
END;
/


--TABLA DE AUDITORIA PARA GUARDAR EL HISTORIAL DE CAMBIOS EN LOS PRODUCTOS
CREATE TABLE AUDITORIA_PRODUCTOS (
    ID_LOG NUMBER PRIMARY KEY,
    ACCION VARCHAR2(20),
    ID_PRODUCTO NUMBER,
    FECHA TIMESTAMP DEFAULT SYSTIMESTAMP,
    USUARIO_DB VARCHAR2(50)
);

CREATE SEQUENCE SEQ_AUDITORIA START WITH 1 INCREMENT BY 1;


CREATE OR REPLACE TRIGGER TRG_AUDITORIA_PROD
AFTER INSERT OR UPDATE OR DELETE ON PRODUCTOS_TIENDA
FOR EACH ROW
DECLARE
    v_accion VARCHAR2(20);
    v_id_prod NUMBER;
BEGIN
    IF INSERTING THEN
        v_accion := 'INSERTAR';
        v_id_prod := :NEW.ID_PRODUCTO;
    ELSIF UPDATING THEN
        v_accion := 'ACTUALIZAR';
        v_id_prod := :NEW.ID_PRODUCTO;
    ELSIF DELETING THEN
        v_accion := 'ELIMINAR';
        v_id_prod := :OLD.ID_PRODUCTO;
    END IF;

    INSERT INTO AUDITORIA_PRODUCTOS (ID_LOG, ACCION, ID_PRODUCTO, USUARIO_DB)
    VALUES (SEQ_AUDITORIA.NEXTVAL, v_accion, v_id_prod, USER);
END;
/


